[[redirects]]
  from = "/auth/callback"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = true
