[build]
  publish = "public"

[[redirects]]
  from = "/.well-known/*"
  to = "/well-known/:splat"
  status = 200
[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
